name: Run e2e
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
      - "**"

concurrency:
  group: ${{ github.ref }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: e2e
    steps:
      - name: Flag e2e as done
        run: echo "e2e is done"
