name: Prebuild common

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #     - "**"
  #   paths:
  #     - src/common/**
  # pull_request_target:
  #   paths:
  #     - src/common/**
  # push:
  #   paths:
  #     - src/common/**
  pull_request:
    types:
      - opened
      - edited
    paths:
      - src/common/**

jobs:
  prebuild-common:
    runs-on: ubuntu-latest
    steps:
      - name: Flag prebuilds as done
        run: echo "prebuilds are done"
